import {test,expect} from '@playwright/test';
for(const viewport of [{width:844,height:304},{width:932,height:430},{width:390,height:740}]){
 test(`installed app menu tour ${viewport.width}x${viewport.height}`,async({browser})=>{
  const context=await browser.newContext({viewport,isMobile:true,hasTouch:true});
  await context.addInitScript(()=>Object.defineProperty(navigator,'standalone',{get:()=>true}));
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  const shot=async name=>{await page.evaluate(()=>document.fonts.ready);await page.screenshot({animations:'disabled',path:`test-results/installed-${name}-${viewport.width}.png`});};
  await page.goto('/');await shot('title');
  for(const button of await page.locator('.stadium-menu button').all())await expect(button).toBeInViewport({ratio:1});
  expect(await page.locator('#start-screen').evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);
  await page.getByRole('button',{name:'Team Editor',exact:true}).tap();await shot('uniform');
  await expect(page.locator('#team-editor-save')).toBeInViewport({ratio:1});
  await page.locator('[data-color-picker="uniform.home.jersey"]').fill('#334455');
  await page.getByRole('button',{name:'away',exact:true}).tap();
  await page.locator('[data-color-picker="uniform.away.jersey"]').fill('#ddeeff');
  await page.getByRole('button',{name:'home',exact:true}).tap();
  await expect(page.locator('[data-color-text="uniform.home.jersey"]')).toHaveValue('#334455');
  await page.getByRole('button',{name:'Save team',exact:true}).tap();
  await expect(page.locator('#team-editor-status')).toContainText('Team saved');
  await page.locator('#team-editor-select-app-control').tap();await shot('team-picker');
  await expect(page.locator('#app-select-title')).toHaveText('Team');
  await expect(page.locator('#app-select-search')).not.toBeFocused();
  await page.locator('#app-select-search').fill('Seattle');await shot('team-search');
  await page.locator('#app-select-sheet .app-select-close').tap();await page.locator('#team-editor-cancel').tap();
  await page.locator('#btn-menu-settings').tap();await shot('settings');await page.locator('#btn-setup-close').tap();
  await page.locator('#btn-career').tap();await shot('career-menu');await page.locator('#career-new').tap();
  await page.getByLabel('Player name',{exact:true}).fill('App Review');await shot('creation');
  await page.getByRole('button',{name:'Choose face',exact:true}).tap();await shot('faces');await page.getByRole('button',{name:'Tan',exact:true}).tap();await page.locator('#portrait-confirm').tap();await expect(page.locator('#career-skin-app-control')).toHaveText('Tan');
  await page.getByRole('button',{name:'Next',exact:true}).tap();await shot('season');
  await page.getByRole('button',{name:'Choose your school',exact:true}).tap();await shot('schools');await page.locator('#school-confirm').tap();
  await page.locator('#career-begin').tap();await shot('home');
  await page.getByRole('tab',{name:'Player',exact:true}).tap();await shot('player');
  await page.getByRole('button',{name:'Stats',exact:true}).tap();await shot('stats');
  await page.getByRole('button',{name:'Career story',exact:true}).tap();await shot('story');await page.locator('#career-progress-close').tap();
  await page.getByRole('tab',{name:'My Team',exact:true}).tap();await shot('roster');
  await page.locator('.roster-card').nth(1).tap();await shot('teammate');await expect(page.locator('.player-passport')).toBeInViewport();
  await page.locator('#teammate-edit-name').tap();await shot('rename');await page.locator('#teammate-cancel-name').tap();
  await page.locator('#teammate-edit-face').tap();await shot('teammate-faces');await page.locator('#portrait-cancel').tap();
  await expect(page.locator('#team-player-dialog')).toBeVisible();
  if(await page.locator('#team-player-dialog').isVisible())await page.locator('#team-player-close').tap();
  await page.getByRole('tab',{name:'League',exact:true}).tap();await shot('league');
  await page.getByRole('button',{name:'Filters',exact:true}).tap();await shot('filters');await page.locator('#league-filters-close').tap();
  await page.getByRole('tab',{name:'Home',exact:true}).tap();await page.getByRole('button',{name:'Play next game',exact:true}).tap();await shot('pregame');
  expect(errors).toEqual([]);await context.close();
 });
}
