import assert from 'node:assert/strict';
import {makeAccountStorage,OWNER_KEY,CACHE_PREFIX,SAVE_KEYS} from '../src/cloud/storage.js';
import {mergePayload} from '../src/cloud/sync.js';
import {createCareer} from '../src/career/career.js';
import {handle,validatePayload} from '../server/worker.js';
const memory=()=>{const map=new Map();return {getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,String(v)),removeItem:k=>map.delete(k)};};
const disk=memory();disk.setItem(SAVE_KEYS[0],'guest original');const guest=makeAccountStorage(disk);assert.equal(guest.getItem(SAVE_KEYS[0]),'guest original');
disk.setItem(OWNER_KEY,'alice');assert.throws(()=>guest.setItem(SAVE_KEYS[0],'stale'),/Account changed/);
const a=makeAccountStorage(disk);assert.equal(a.getItem(SAVE_KEYS[0]),null);a.setItem(SAVE_KEYS[0],'alice save');const sent=a.snapshot();a.setItem(SAVE_KEYS[0],'newer save');a.acknowledge(sent,1);assert.equal(a.snapshot().dirty,true);assert.equal(a.getItem(SAVE_KEYS[0]),'newer save');
assert.equal(a.install({revision:2,payload:{}},sent),false);const second=makeAccountStorage(disk);second.setItem(SAVE_KEYS[0],'other tab');assert.throws(()=>a.setItem(SAVE_KEYS[0],'stale'),/another tab/);
disk.setItem(OWNER_KEY,'bob');const b=makeAccountStorage(disk);assert.equal(b.getItem(SAVE_KEYS[0]),null);assert.equal(disk.getItem(SAVE_KEYS[0]),'guest original');
const c=createCareer({name:'Saved QB'});const payload={[SAVE_KEYS[0]]:JSON.stringify({version:1,lastId:c.careerId,careers:{[c.careerId]:c},recovery:[]}),[SAVE_KEYS[1]]:JSON.stringify(c)};
const modified=structuredClone(c);modified.xp=9;const other={[SAVE_KEYS[0]]:JSON.stringify({version:1,lastId:c.careerId,careers:{[c.careerId]:modified},recovery:[]})};
const merged=mergePayload(payload,other);assert.equal(Object.keys(JSON.parse(merged[SAVE_KEYS[0]]).careers).length,2);validatePayload(merged);assert.equal(Object.keys(JSON.parse(mergePayload(payload,payload)[SAVE_KEYS[0]]).careers).length,1);
const host='https://feat-cloud-career-saves-gridiron-legends.jacobchapman3.workers.dev';
let calls=0;
const backend=async(url,opts)=>{calls++;if(url.endsWith('/get-session'))return Response.json({user:{id:'alice',emailVerified:true},session:{token:'secret'}});if(url.endsWith('/token'))return Response.json({token:'jwt'});if(url.endsWith('/career_cloud_write')){assert.equal(opts.headers.Authorization,'Bearer jwt');return Response.json({revision:1});}return Response.json({revision:0,payload:null});};
assert.equal((await handle(new Request(host+'/api/cloud',{method:'PUT',body:'{}',headers:{Origin:'https://evil.example'}}),{},backend)).status,403);assert.equal(calls,0);
assert.equal((await handle(new Request(host+'/api/cloud',{headers:{'X-Career-Owner':'bob'}}),{},backend)).status,409);
const request=new Request(host+'/api/cloud',{method:'PUT',headers:{Origin:host,'X-Career-Owner':'alice'},body:JSON.stringify({revision:0,mutation:'save-123456',payload})});assert.equal((await handle(request,{},backend)).status,200);
const result=await handle(new Request(host+'/api/auth/get-session'),{},backend);const json=await result.json();assert.equal(json.session.token,undefined);
assert.equal((await handle(new Request(host+'/api/auth/sign-up/email',{method:'POST',headers:{Origin:host},body:'{}'}),{},backend)).status,404);
const unauthorized=async()=>Response.json(null);assert.equal((await handle(new Request(host+'/api/cloud'),{},unauthorized)).status,401);
console.log('Cloud checks passed: guest preservation, account isolation, stale tabs, pending writes, conflict copies, payload validation, origin checks, session isolation and token redaction.');
