const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderDraftNight(c,draft,team,helmet){
 const report=draft.report,p=report.projection,s=report.stats,r=report.rating;
 const boosts=p.boosts||[];
 document.getElementById('draft-selection').innerHTML=`
 <section id="draft-panel-season" role="tabpanel" aria-labelledby="draft-tab-season" hidden><div class="draft-columns"><div><span class="sports-kicker">Senior season review</span><h3>${esc(report.school)}</h3><p>Regular season: ${report.record.wins}–${report.record.losses}</p><p>Final college overall <b>${r.collegeOverall}</b></p><p>Full senior season: ${s.passingYards} passing yards · ${s.passingTD} passing TD · ${s.interceptions} INT · ${s.rushingYards} rushing yards</p></div><div><h3>Your honors</h3>${report.awards.length?`<ul>${report.awards.map(a=>`<li>${esc(a)}</li>`).join('')}</ul>`:'<p>No individual or team awards earned.</p>'}<p>${report.honors?.mvp?`College MVP: ${esc(report.honors.mvp.name)} (${esc(report.honors.mvp.team)}).`:'MVP unavailable: not enough qualifying regular-season statistics.'}</p></div></div></section>
 <section id="draft-panel-scouting" role="tabpanel" aria-labelledby="draft-tab-scouting" hidden><div class="draft-columns"><div><h3>Scouting report</h3><h4>Strengths</h4>${report.strengths.length?`<ul>${report.strengths.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>Scouts need a larger body of work.</p>'}<h4>Development priorities</h4>${report.concerns.length?`<ul>${report.concerns.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>Strong college profile. Adjust to the faster pro game.</p>'}</div><div><h3>Award impact</h3><p>Performance projection: pick ${p.basePick??p.pick}</p>${boosts.map(b=>`<p class="draft-boost"><b>${esc(b.title)}</b><br>Pick ${b.before} → ${b.after}${b.places?` · improved ${b.places} places`:' · already near the top'}</p>`).join('')||'<p>No award bonuses applied.</p>'}<p><b>Final projection: pick ${p.pick}</b></p><p class="draft-note">MVP compares qualifying offensive players across the league using regular-season efficiency, production, ball security and wins. Award bonuses stack with diminishing returns near No. 1. Team need can move the actual selection a few places.</p></div></div></section>
 <section id="draft-panel-selection" role="tabpanel" aria-labelledby="draft-tab-selection"><div class="draft-columns"><div class="draft-team"><p class="sports-kicker">ROUND ${draft.round} · PICK ${draft.pick}</p>${helmet(team)}<h3>${esc(team.city)} ${esc(team.name)}</h3><p>${report.contractYears}-year rookie contract · Starting quarterback</p></div><div><h3>Why this team?</h3><p>${esc(report.selectionReason)}</p><p>College overall ${r.collegeOverall} → Pro overall ${r.overall}</p><p>Your college story and awards stay with you.</p></div></div></section>
 <section id="draft-panel-rookie" role="tabpanel" aria-labelledby="draft-tab-rookie" hidden><div class="draft-columns"><div><h3>Your pro starting point</h3><p>College overall ${r.collegeOverall} → Pro overall ${r.overall}</p><div class="draft-attributes">${Object.entries(r.attributes).map(([k,v])=>`<span>${esc(k==='arm'?'Arm strength':k)} <b>${v}</b></span>`).join('')}</div><p>${c.progressionVersion===2?'Development speed stays with you. Unspent college points convert at 3:1; leftover value becomes XP.':'Your original attribute carryover is preserved.'}</p><h3>Supporting cast</h3>${report.teammates.map(t=>`<p>${esc(t.slot)} · ${esc(t.name)} · ${t.rating} OVR</p>`).join('')}</div><div><h3>Rookie season targets</h3><ul>${report.expectations.map(e=>`<li>${esc(e.label)}</li>`).join('')}</ul><p class="draft-note">Build your first regular season around efficient passing, ball security and team success.</p></div></div></section>`;
 const tabs=[...document.querySelectorAll('[data-draft-page]')];
 const select=page=>{
  for(const tab of tabs){const active=tab.dataset.draftPage===page;tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1;document.getElementById(`draft-panel-${tab.dataset.draftPage}`).hidden=!active;}
  document.getElementById('draft-selection').scrollTop=0;
 };
 for(const [i,tab] of tabs.entries()){
  tab.onclick=()=>select(tab.dataset.draftPage);
  tab.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;select(tabs[next].dataset.draftPage);tabs[next].focus();};
 }
 select('selection');
}
