import * as Career from '../career/career.js';
import * as League from '../state/league.js';
import {playingRoster} from '../career/roster.js';
import {collegeStandings} from '../career/college.js';
import {paintPlayerPortrait} from './playerPortrait.js';

const el=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const name=p=>[p?.firstName,p?.lastName].filter(Boolean).join(' ');
const record=t=>`${t?.record?.wins??0}-${t?.record?.losses??0}${t?.record?.ties?'-'+t.record.ties:''}`;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));

let view='home',playerView='attributes',leagueView='standings',snapshot=null,root=null,refreshQueued=false;

const STYLE=`
@font-face{font-family:MCAPixel;src:url('/assets/ui/Jersey10-Regular.ttf') format('truetype');font-display:swap}
#career-screen.mobile-app-active{padding:0!important;position:relative!important;overflow:hidden!important;background:#031634!important}
#career-screen.mobile-app-active>.career-panel>.career-header,
#career-screen.mobile-app-active>.career-panel>#career-hub,
#career-screen.mobile-app-active>.career-panel>.career-nav{display:none!important}
#mobile-career-app{--bg:#031634;--panel:#05245a;--panel2:#062d6a;--line:#0b7ff0;--line2:#2396ff;--yellow:#ffe000;--white:#f6f9ff;--muted:#9fc4f3;position:absolute;inset:0;z-index:20;display:flex;flex-direction:column;background:linear-gradient(180deg,#052356 0,#031735 100%);color:var(--white);font-family:Arial,sans-serif;overflow:hidden;touch-action:manipulation}
#mobile-career-app[hidden]{display:none!important}
#mobile-career-app button{font-family:MCAPixel,"Courier New",monospace;text-transform:uppercase;cursor:pointer}
.mca-header{height:68px;flex:0 0 68px;display:grid;grid-template-columns:minmax(210px,.8fr) 1.35fr 70px;align-items:center;gap:12px;padding:6px 18px;background:linear-gradient(180deg,#0759bf,#07499e);border-top:2px solid #0d8cff;border-bottom:3px solid #0f83eb;box-shadow:0 3px 0 #020d25}
.mca-profile{display:grid;grid-template-columns:52px 1fr;align-items:center;gap:10px;min-width:0}.mca-profile canvas{width:52px;height:52px;image-rendering:pixelated;background:#06366f;border:2px solid #2396ff;box-shadow:inset 0 0 0 2px #04285c}.mca-profile-name{font:900 28px/.9 MCAPixel,"Courier New";white-space:nowrap;overflow:hidden;text-overflow:ellipsis;text-shadow:2px 2px #062455}.mca-profile-meta{margin-top:5px;font:900 12px/1 MCAPixel,"Courier New";color:#d5e5ff;letter-spacing:.06em}.mca-profile-meta b{color:var(--yellow)}
.mca-page-title{text-align:center;min-width:0}.mca-page-title strong{display:block;font:900 31px/.9 MCAPixel,"Courier New";letter-spacing:.05em;text-shadow:2px 2px #05204c;white-space:nowrap}.mca-page-title strong:before,.mca-page-title strong:after{content:'★';color:var(--yellow);font-size:18px;vertical-align:4px;margin:0 14px}.mca-page-title span{display:block;margin-top:6px;font:900 12px/1 MCAPixel,"Courier New";letter-spacing:.07em;color:#c6dcff;white-space:nowrap}
.mca-menu{justify-self:end;width:54px;height:50px;border:3px solid #fff;background:#073a80;color:#fff4bf;font-size:25px;box-shadow:inset 0 0 0 2px #126dce}
.mca-stage{flex:1;min-height:0;padding:10px 16px 8px;overflow:hidden}.mca-screen{height:100%;min-height:0;display:flex;flex-direction:column;gap:8px}.mca-panel{border:2px solid var(--line);background:linear-gradient(180deg,#06285f,#041e49);box-shadow:inset 0 0 0 1px #02142f;min-width:0;min-height:0}
.mca-subtabs{height:48px;flex:0 0 48px;display:grid;grid-template-columns:repeat(3,1fr);border:2px solid var(--line);background:linear-gradient(180deg,#06285f,#051e49)}.mca-subtabs button{border:0;border-right:1px solid #0d69ce;border-bottom:5px solid transparent;background:transparent;color:#aac8ed;font-size:15px}.mca-subtabs button:last-child{border-right:0}.mca-subtabs button.active{color:var(--yellow);border-bottom-color:var(--yellow)}
.mca-home-timeline{height:58px;flex:0 0 58px;display:grid;grid-template-columns:1fr 1.35fr 1fr}.mca-timeline-cell{position:relative;display:flex;flex-direction:column;justify-content:center;padding:8px 14px;border-right:1px solid #0c68ce;min-width:0}.mca-timeline-cell:last-child{border-right:0}.mca-timeline-cell small{font:900 11px/1 MCAPixel,"Courier New";color:#93b8e8;letter-spacing:.08em}.mca-timeline-cell strong{margin-top:5px;font:900 15px/1 MCAPixel,"Courier New";white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.mca-timeline-cell.current{text-align:center;align-items:center}.mca-timeline-cell.current strong{color:var(--yellow);font-size:16px}.mca-progress{position:absolute;left:16%;right:16%;bottom:7px;height:7px;background:#02183b;border:1px solid var(--line)}.mca-progress i{display:block;height:100%;width:38%;background:var(--yellow)}
.mca-home-grid{flex:1;min-height:0;display:grid;grid-template-columns:minmax(0,1.42fr) minmax(210px,.78fr) minmax(225px,.82fr);gap:8px}.mca-match{position:relative;display:flex;flex-direction:column;padding:8px 12px;background:linear-gradient(180deg,rgba(1,18,45,.08),rgba(1,14,35,.45)),repeating-linear-gradient(90deg,rgba(10,89,69,.55) 0 32px,rgba(5,68,58,.55) 32px 64px),linear-gradient(180deg,#07345f 0 43%,#075249 43% 100%)}.mca-match:before,.mca-match:after{content:'✦✦✦';position:absolute;top:22px;color:#d3ebff;text-shadow:0 0 8px #8fd7ff;font-size:18px;letter-spacing:-5px}.mca-match:before{left:22px}.mca-match:after{right:22px}.mca-kicker{text-align:center;font:900 13px/1 MCAPixel,"Courier New";color:#b4d1f4;letter-spacing:.12em;z-index:1}.mca-kicker:before,.mca-kicker:after{content:'';display:inline-block;width:62px;height:2px;background:#b4d1f4;margin:0 10px;vertical-align:4px;opacity:.8}.mca-matchup{flex:1;min-height:0;display:grid;grid-template-columns:1fr 56px 1fr;align-items:center;z-index:1}.mca-side{text-align:center}.mca-side strong{display:block;font:900 31px/.9 MCAPixel,"Courier New";text-shadow:2px 2px #03152e}.mca-side span{display:block;font:900 12px/1 MCAPixel,"Courier New"}.mca-vs{text-align:center;font:900 25px/1 MCAPixel,"Courier New"}.mca-helmet{position:relative;width:74px;height:62px;margin:0 auto 6px;border-radius:45px 40px 18px 20px;background:var(--helmet,#2f6df0);border:4px solid #031a3a;box-shadow:3px 4px 0 rgba(0,0,0,.38)}.mca-helmet:before{content:'';position:absolute;left:30px;top:0;width:12px;height:62px;background:var(--stripe,#fff);opacity:.95}.mca-helmet:after{content:'';position:absolute;right:-14px;bottom:8px;width:28px;height:16px;border:4px solid #dbe8f5;border-left:0;background:transparent}.mca-helmet b{position:absolute;inset:20px 10px auto 10px;font:900 12px/1 MCAPixel,"Courier New";color:#fff;z-index:2;text-shadow:1px 1px #000}.mca-play{height:50px;flex:0 0 50px;border:3px solid #fff;background:linear-gradient(180deg,#ffed31,#ffd500);color:#061633;font-size:16px;box-shadow:0 4px 0 #02122b}.mca-play:before{content:'▶';margin-right:12px}
.mca-card-title{height:42px;display:flex;align-items:center;justify-content:space-between;padding:0 12px;border-bottom:1px solid #0b6ed8;font:900 17px/1 MCAPixel,"Courier New"}.mca-card-title small{font-size:9px;color:#a7c6eb}.mca-challenge{display:flex;flex-direction:column}.mca-challenge-copy{padding:12px;display:grid;grid-template-columns:44px 1fr auto;align-items:center;gap:10px;font-weight:700}.mca-check{font-size:34px;color:var(--yellow)}.mca-xp{font:900 15px/1 MCAPixel,"Courier New";color:var(--yellow);border:2px solid var(--line);padding:7px 8px}.mca-metrics{margin:auto 10px 10px;padding-top:10px;border-top:1px solid #0b6ed8;display:grid;grid-template-columns:repeat(3,1fr);gap:6px;text-align:center}.mca-metrics b{display:block;font:900 25px/1 MCAPixel,"Courier New";color:var(--yellow)}.mca-metrics span{font-size:11px;color:#b9d2f3}.mca-standings-list{padding:4px 10px}.mca-standing{display:grid;grid-template-columns:26px 1fr auto;gap:7px;padding:9px 4px;border-bottom:1px solid #0b63bf;align-items:center;font-size:12px}.mca-standing.you{color:var(--yellow);background:#07367f;border:1px solid var(--line);margin-top:-1px}.mca-standing b{font-weight:800}
.mca-player-grid{flex:1;min-height:0;display:grid;grid-template-columns:235px minmax(0,1fr);gap:8px}.mca-player-profile{padding:12px;text-align:center;display:flex;flex-direction:column;align-items:center}.mca-player-profile canvas{width:132px;height:132px;image-rendering:pixelated;background:#07376f;border:2px solid #83baff}.mca-player-profile h2{font:900 26px/.9 MCAPixel,"Courier New";margin:8px 0 4px}.mca-player-profile p{margin:3px 0;color:#bed5f4;font:900 12px/1 MCAPixel,"Courier New"}.mca-xpbar,.mca-ratingbar{height:9px;background:#021a40;border:1px solid #0a6edb;overflow:hidden}.mca-xpbar{width:90%;margin-top:10px}.mca-xpbar i,.mca-ratingbar i{display:block;height:100%;background:var(--yellow)}.mca-player-profile .mca-profile-detail{width:90%;margin-top:9px;padding-top:8px;border-top:1px solid #0b6bcf;font-size:11px;line-height:1.45;color:#b8d1f1;text-align:left}.mca-attributes{padding:10px 12px;overflow:auto}.mca-attr-heading{height:44px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #0b6bd0}.mca-attr-heading h2{font:900 21px/1 MCAPixel,"Courier New";margin:0}.mca-points{background:var(--yellow);color:#061634;padding:8px 11px;font:900 12px/1 MCAPixel,"Courier New"}.mca-attr-row{display:grid;grid-template-columns:48px minmax(140px,.75fr) 58px minmax(135px,1fr) 126px;align-items:center;gap:8px;min-height:65px;padding:6px;border-bottom:1px solid #0b5cae}.mca-attr-icon{display:grid;place-items:center;width:42px;height:42px;border:2px solid var(--line);background:#073c85;font-size:22px}.mca-attr-name{font:900 19px/.9 MCAPixel,"Courier New"}.mca-attr-desc{margin-top:4px;color:#74a8e7;font-size:10px;text-transform:uppercase}.mca-attr-value{font:900 29px/1 MCAPixel,"Courier New";color:var(--yellow);text-align:center}.mca-upgrade{min-height:46px;border:2px solid #72a0c8;background:#315d79;color:#fff;font-size:13px}.mca-upgrade:disabled{opacity:.45}.mca-upgrade small{display:block;font-size:9px;margin-top:4px}.mca-stat-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;padding:15px}.mca-stat{padding:18px;text-align:center}.mca-stat b{display:block;font:900 29px/1 MCAPixel,"Courier New";color:var(--yellow)}.mca-stat span{display:block;margin-top:6px;color:#b8d1f2;font-size:12px}.mca-story{padding:16px;overflow:auto}.mca-story h2{font:900 23px/1 MCAPixel,"Courier New"}.mca-story p{color:#c1d6f3;line-height:1.5}
.mca-team-head{height:88px;flex:0 0 88px;display:flex;align-items:center;justify-content:space-between;padding:0 16px}.mca-team-head h1{margin:0;font:900 31px/.9 MCAPixel,"Courier New"}.mca-team-head p{margin:7px 0 0;color:#b8d0f0;font:900 12px/1 MCAPixel,"Courier New";letter-spacing:.14em}.mca-team-editor{min-height:42px;padding:0 15px;border:2px solid var(--line);background:#07356f;color:#fff;font-size:13px}.mca-roster{flex:1;min-height:0;overflow:auto;display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:7px;padding:0 5px 5px}.mca-player-card{min-height:150px;padding:7px 6px;border:2px solid var(--line);background:linear-gradient(180deg,#06285f,#041f4b);color:#fff;text-align:center}.mca-player-card canvas{width:72px;height:72px;image-rendering:pixelated;background:#07376f}.mca-player-card .pos{font:900 12px/1 MCAPixel,"Courier New"}.mca-player-card strong{display:block;margin-top:4px;font:900 14px/1 MCAPixel,"Courier New";white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.mca-player-card .ovr{display:block;margin:4px 0 6px;font:900 11px/1 MCAPixel,"Courier New"}.mca-player-card.you .pos{color:var(--yellow)}
.mca-league-body{flex:1;min-height:0;overflow:auto;padding:8px 10px}.mca-league-title{font:900 28px/.9 MCAPixel,"Courier New";margin:0}.mca-league-sub{color:#b8d1f2;margin:7px 0 12px}.mca-confs{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.mca-conf{padding:8px 10px}.mca-conf h3{font:900 18px/1 MCAPixel,"Courier New";margin:0 0 5px}.mca-leader-row{display:grid;grid-template-columns:1fr auto;gap:10px;padding:11px 5px;border-bottom:1px solid #0b65c4}.mca-schedule{display:grid;gap:6px}.mca-game-row{display:grid;grid-template-columns:1fr auto;gap:12px;padding:11px 8px;border-bottom:1px solid #0b65c4}
.mca-nav{height:58px;flex:0 0 58px;display:grid;grid-template-columns:repeat(4,1fr);background:#05295f;border-top:2px solid #0c79e5}.mca-nav button{position:relative;border:0;border-right:1px solid #0b6ed1;background:transparent;color:#c3d8f5;font-size:14px}.mca-nav button:last-child{border-right:0}.mca-nav button.active{color:var(--yellow)}.mca-nav button.active:after{content:'';position:absolute;left:17%;right:17%;bottom:0;height:5px;background:var(--yellow)}.mca-nav i{font-style:normal;font-family:Arial,sans-serif;font-size:21px;margin-right:9px}
@media(max-height:420px){.mca-header{height:58px;flex-basis:58px;padding-top:4px;padding-bottom:4px}.mca-profile canvas{width:44px;height:44px}.mca-profile{grid-template-columns:44px 1fr}.mca-profile-name{font-size:23px}.mca-profile-meta,.mca-page-title span{font-size:10px}.mca-page-title strong{font-size:26px}.mca-stage{padding:7px 12px 5px}.mca-home-timeline{height:50px;flex-basis:50px}.mca-home-grid{grid-template-columns:minmax(0,1.42fr) minmax(195px,.78fr) minmax(210px,.82fr)}.mca-helmet{width:60px;height:50px}.mca-helmet:before{height:50px}.mca-matchup{grid-template-columns:1fr 48px 1fr}.mca-side strong{font-size:25px}.mca-play{height:43px;flex-basis:43px}.mca-nav{height:48px;flex-basis:48px}.mca-nav button{font-size:12px}.mca-player-grid{grid-template-columns:205px 1fr}.mca-player-profile canvas{width:106px;height:106px}.mca-attr-row{min-height:54px;grid-template-columns:42px minmax(125px,.75fr) 50px minmax(120px,1fr) 112px}.mca-attr-icon{width:36px;height:36px}.mca-attr-name{font-size:16px}.mca-team-head{height:70px;flex-basis:70px}.mca-player-card{min-height:126px}.mca-player-card canvas{width:58px;height:58px}}
@media(orientation:portrait){#mobile-career-app:after{content:'Rotate your phone to landscape';position:absolute;inset:0;z-index:100;background:#031634;display:grid;place-items:center;color:#fff;font:900 24px/1.2 MCAPixel,"Courier New";text-align:center;padding:30px}}
`;

function attrLabel(key){return key==='arm'?'ARM STRENGTH':String(key).replace(/([A-Z])/g,' $1').toUpperCase();}
function attrDesc(key){return {accuracy:'Hit your target',arm:'Throw it further',release:'Get it off quick',speed:'Extend the play',mobility:'Extend the play',stamina:'Stay sharp'}[key]||'Build your game';}
function attrIcon(key){return {accuracy:'◎',arm:'◒',release:'◈',speed:'↗',mobility:'↗',stamina:'◆'}[key]||'◆';}
function stageLabel(c){return c.stage==='college'?'COLLEGE SENIOR':'PRO CAREER';}
function seasonLine(c,team){return `${stageLabel(c)} · ${c.postseason?'PLAYOFFS':`WEEK ${c.league.week} / ${c.stage==='college'?12:17}`} · ${record(team)}`;}
function getStanding(c,conf){return c.stage==='college'?collegeStandings(c,conf):League.standings(c.league,conf);}
function buildSnapshot(){
 const screen=el('career-screen'),hub=el('career-hub'),create=el('career-create');
 if(!screen?.classList.contains('show')||!hub||hub.hidden||!create?.hidden)return null;
 const career=Career.loadCareer();if(!career)return null;
 const player=Career.careerPlayer(career),team=League.findTeamState(career.league,career.teamId),match=Career.nextMatch(career);
 if(!player||!team)return null;
 const opponent=match?League.findTeamState(career.league,match.homeTeamId===career.teamId?match.awayTeamId:match.homeTeamId):null;
 const standings=getStanding(career,team.conference),roster=playingRoster(team);
 const confs=[...new Set((career.league.teams||[]).map(t=>t.conference).filter(Boolean))];
 const orderedConfs=[team.conference,...confs.filter(c=>c!==team.conference)];
 return {career,player,team,match,opponent,standings,roster,conferences:orderedConfs};
}
function teamColors(t){return `--helmet:${t?.colors?.primary||'#2869d9'};--stripe:${t?.colors?.secondary||'#fff'}`;}
function header(s,title){return `<header class="mca-header"><div class="mca-profile"><canvas data-role="header-portrait" width="64" height="64"></canvas><div><div class="mca-profile-name">${esc(name(s.player))}</div><div class="mca-profile-meta"><b>LV ${s.career.level}</b> · ${s.career.xp}/100 XP · ${s.career.points} ${s.career.points===1?'POINT':'POINTS'}</div></div></div><div class="mca-page-title"><strong>${title}</strong><span>${esc(seasonLine(s.career,s.team))}</span></div><button class="mca-menu" data-action="menu" aria-label="Career menu">☰</button></header>`;}
function timeline(s){const last=s.career.lastResult?`${s.career.lastResult.userScore>s.career.lastResult.cpuScore?'Win':'Loss'} ${s.career.lastResult.userScore}-${s.career.lastResult.cpuScore}`:'Season start';const next=s.opponent?`${s.match?.homeTeamId===s.career.teamId?'vs':'at'} ${s.opponent.city} ${s.opponent.name}`:'Season complete';return `<section class="mca-home-timeline mca-panel"><div class="mca-timeline-cell"><small>LAST</small><strong>${esc(last)}</strong></div><div class="mca-timeline-cell current"><small>NOW</small><strong>${esc(seasonLine(s.career,s.team))}</strong><span class="mca-progress"><i></i></span></div><div class="mca-timeline-cell"><small>NEXT</small><strong>${esc(next)}</strong></div></section>`;}
function standingRows(s,rows=s.standings.slice(0,4)){return rows.map((t,i)=>`<div class="mca-standing ${t.id===s.team.id?'you':''}"><span>${i+1}</span><span>${esc(t.abbr)} ${esc(t.name)}</span><b>${esc(record(t))}</b></div>`).join('');}
function homeScreen(s){const a=s.career.seasonStats,cmp=a.attempts?Math.round(a.completions/a.attempts*100):0;return `<div class="mca-screen">${timeline(s)}<div class="mca-home-grid"><section class="mca-match mca-panel"><div class="mca-kicker">NEXT GAME</div><div class="mca-matchup"><div class="mca-side"><div class="mca-helmet" style="${teamColors(s.team)}"><b>${esc(s.team.abbr)}</b></div><strong>${esc(s.team.abbr)}</strong><span>${esc(record(s.team))}</span></div><div class="mca-vs">VS</div><div class="mca-side"><div class="mca-helmet" style="${teamColors(s.opponent)}"><b>${esc(s.opponent?.abbr||'--')}</b></div><strong>${esc(s.opponent?.abbr||'--')}</strong><span>${esc(s.opponent?record(s.opponent):'')}</span></div></div><button class="mca-play" data-action="play" ${s.match?'':'disabled'}>${s.career.checkpoint?'RESUME GAME':'PLAY NEXT GAME'}</button></section><section class="mca-challenge mca-panel"><div class="mca-card-title"><span>WEEKLY CHALLENGE</span><span class="mca-xp">GAME DAY</span></div><div class="mca-challenge-copy"><span class="mca-check">☑</span><span>Win your matchup and build your quarterback.</span></div><div class="mca-metrics"><div><b>${cmp}%</b><span>COMPLETIONS</span></div><div><b>${a.interceptions}</b><span>INT</span></div><div><b>${a.attempts}</b><span>ATTEMPTS</span></div></div></section><section class="mca-panel"><div class="mca-card-title"><span>CONFERENCE STANDINGS</span><small>VIEW FULL ›</small></div><div class="mca-standings-list">${standingRows(s)}</div></section></div></div>`;}
function playerStats(s){const a=s.career.seasonStats,t=s.career.totals;return `<div class="mca-stat-grid"><div class="mca-stat mca-panel"><b>${a.passingYards}</b><span>SEASON PASS YDS</span></div><div class="mca-stat mca-panel"><b>${a.passingTD}</b><span>SEASON TD</span></div><div class="mca-stat mca-panel"><b>${a.interceptions}</b><span>SEASON INT</span></div><div class="mca-stat mca-panel"><b>${t.passingYards}</b><span>CAREER PASS YDS</span></div><div class="mca-stat mca-panel"><b>${t.passingTD}</b><span>CAREER TD</span></div><div class="mca-stat mca-panel"><b>${t.games}</b><span>CAREER GAMES</span></div></div>`;}
function playerAttributes(s){const rows=Object.entries(s.player.attributes||{}).map(([key,value])=>`<div class="mca-attr-row"><span class="mca-attr-icon">${attrIcon(key)}</span><div><div class="mca-attr-name">${attrLabel(key)}</div><div class="mca-attr-desc">${attrDesc(key)}</div></div><div class="mca-attr-value">${value}</div><span class="mca-ratingbar"><i style="width:${clamp(value/95*100,0,100)}%"></i></span><button class="mca-upgrade" data-upgrade="${esc(key)}" ${s.career.points<1||s.career.activeMatch||value>=95?'disabled':''}>${value>=95?'MAX':'UPGRADE +2'}<small>${value>=95?'':'1 POINT'}</small></button></div>`).join('');return `<div class="mca-player-grid"><section class="mca-player-profile mca-panel"><canvas data-role="player-portrait" width="128" height="128"></canvas><h2>${esc(name(s.player))}</h2><p>#${s.player.number} · QB · LV ${s.career.level}</p><span class="mca-xpbar"><i style="width:${s.career.xp}%"></i></span><p>${s.career.xp}/100 XP</p><div class="mca-profile-detail">${esc(s.team.city)} ${esc(s.team.name)}<br>${stageLabel(s.career)}<br>${esc(s.player.development||'Normal')} development</div></section><section class="mca-attributes mca-panel"><div class="mca-attr-heading"><h2>DEVELOP YOUR QUARTERBACK</h2><span class="mca-points">${s.career.points} POINTS AVAILABLE</span></div>${rows}</section></div>`;}
function playerStory(s){return `<section class="mca-story mca-panel"><h2>YOUR CAREER STORY</h2><p>${esc(stageLabel(s.career))} · ${esc(s.team.city)} ${esc(s.team.name)}</p><p>Career record: ${esc(record(s.team))}</p><p>${s.career.awards?.length?esc(s.career.awards.map(a=>a.title).join(' · ')):'Your first milestone is still ahead.'}</p><button class="mca-upgrade" data-action="career-story">OPEN FULL CAREER STORY</button></section>`;}
function playerScreen(s){const body=playerView==='attributes'?playerAttributes(s):playerView==='stats'?playerStats(s):playerStory(s);return `<div class="mca-screen"><nav class="mca-subtabs">${[['attributes','ATTRIBUTES'],['stats','STATS'],['career','CAREER STORY']].map(([k,l])=>`<button class="${playerView===k?'active':''}" data-player-view="${k}">${l}</button>`).join('')}</nav>${body}</div>`;}
function teamScreen(s){const cards=s.roster.map(p=>`<button class="mca-player-card ${p.id===s.career.playerId?'you':''}" data-player-id="${esc(p.id)}"><span class="pos">#${p.number} · ${esc(p.position)}${p.id===s.career.playerId?' · YOU':''}</span><canvas width="64" height="64" data-player-canvas="${esc(p.id)}"></canvas><strong>${esc(name(p))}</strong><span class="ovr">${p.rating} OVR</span><span class="mca-ratingbar"><i style="width:${p.rating}%"></i></span></button>`).join('');return `<div class="mca-screen"><section class="mca-team-head mca-panel"><div><h1>${esc(s.team.city)} ${esc(s.team.name)}</h1><p>ROSTER · ${s.roster.length} PLAYERS · ${esc(record(s.team))}</p></div><button class="mca-team-editor" data-action="team-editor">✎ &nbsp; TEAM EDITOR</button></section><div class="mca-roster">${cards}</div></div>`;}
function conferencePanel(s,conf){const rows=getStanding(s.career,conf);return `<section class="mca-conf mca-panel"><h3>${esc(conf||'CONFERENCE')}</h3>${rows.map((t,i)=>`<div class="mca-standing ${t.id===s.team.id?'you':''}"><span>${i+1}</span><span>${esc(t.abbr)} ${esc(t.name)}</span><b>${esc(record(t))}</b></div>`).join('')}</section>`;}
function leadersView(s){const teams=[...(s.career.league.teams||[])].sort((a,b)=>(b.ratings?.overall||0)-(a.ratings?.overall||0)).slice(0,8);return `<div class="mca-league-body"><h1 class="mca-league-title">LEAGUE LEADERS</h1><p class="mca-league-sub">Top overall teams right now.</p><section class="mca-panel">${teams.map((t,i)=>`<div class="mca-leader-row"><span>${i+1}. ${esc(t.abbr)} ${esc(t.name)}</span><b>${t.ratings?.overall??'-'} OVR</b></div>`).join('')}</section></div>`;}
function standingsView(s){const confs=s.conferences.slice(0,2);while(confs.length<2)confs.push(s.team.conference);return `<div class="mca-league-body"><h1 class="mca-league-title">CONFERENCE STANDINGS</h1><p class="mca-league-sub">Top teams move on when the postseason arrives.</p><div class="mca-confs">${conferencePanel(s,confs[0])}${conferencePanel(s,confs[1])}</div></div>`;}
function scheduleView(s){const history=(s.career.history||[]).slice(-8).reverse();return `<div class="mca-league-body"><h1 class="mca-league-title">SCHEDULE</h1><p class="mca-league-sub">Recent results and what comes next.</p><section class="mca-schedule mca-panel">${s.opponent?`<div class="mca-game-row"><span>NEXT · ${esc(s.match?.homeTeamId===s.career.teamId?'vs':'at')} ${esc(s.opponent.city)} ${esc(s.opponent.name)}</span><b>${esc(record(s.opponent))}</b></div>`:''}${history.map(r=>`<div class="mca-game-row"><span>S${r.season} · WEEK ${r.week}</span><b>${r.userScore}-${r.cpuScore}</b></div>`).join('')||'<div class="mca-game-row"><span>Your first game is waiting.</span><b></b></div>'}</section></div>`;}
function leagueScreen(s){const body=leagueView==='leaders'?leadersView(s):leagueView==='schedule'?scheduleView(s):standingsView(s);return `<div class="mca-screen"><nav class="mca-subtabs">${[['leaders','LEADERS'],['standings','STANDINGS'],['schedule','SCHEDULE']].map(([k,l])=>`<button class="${leagueView===k?'active':''}" data-league-view="${k}">${l}</button>`).join('')}</nav>${body}</div>`;}
function nav(){return `<nav class="mca-nav">${[['home','⌂','HOME'],['player','●','PLAYER'],['team','▦','TEAM'],['league','★','LEAGUE']].map(([k,i,l])=>`<button class="${view===k?'active':''}" data-view="${k}"><i>${i}</i>${l}</button>`).join('')}</nav>`;}
function title(){return {home:'CAREER',player:'PLAYER',team:'MY TEAM',league:'LEAGUE'}[view]||'CAREER';}
function renderApp(){if(!root||!snapshot)return;root.style.setProperty('--mca-primary',snapshot.team.colors?.primary||'#2869d9');root.innerHTML=header(snapshot,title())+`<main class="mca-stage">${view==='home'?homeScreen(snapshot):view==='player'?playerScreen(snapshot):view==='team'?teamScreen(snapshot):leagueScreen(snapshot)}</main>`+nav();bind();paint();}
function paint(){if(!snapshot||!root)return;const h=root.querySelector('[data-role="header-portrait"]');if(h)paintPlayerPortrait(h,snapshot.team,snapshot.player);const p=root.querySelector('[data-role="player-portrait"]');if(p)paintPlayerPortrait(p,snapshot.team,snapshot.player);for(const canvas of root.querySelectorAll('[data-player-canvas]')){const player=snapshot.roster.find(p=>p.id===canvas.dataset.playerCanvas);if(player)paintPlayerPortrait(canvas,snapshot.team,player);}}
function proxy(id){const node=el(id);if(node){node.click();setTimeout(queueRefresh,0);}}
function bind(){for(const b of root.querySelectorAll('[data-view]'))b.onclick=()=>{view=b.dataset.view;renderApp();};for(const b of root.querySelectorAll('[data-player-view]'))b.onclick=()=>{playerView=b.dataset.playerView;renderApp();};for(const b of root.querySelectorAll('[data-league-view]'))b.onclick=()=>{leagueView=b.dataset.leagueView;renderApp();};root.querySelector('[data-action="menu"]')?.addEventListener('click',()=>proxy('career-menu-open'));root.querySelector('[data-action="play"]')?.addEventListener('click',()=>proxy('career-play'));root.querySelector('[data-action="team-editor"]')?.addEventListener('click',()=>proxy('career-team-editor'));root.querySelector('[data-action="career-story"]')?.addEventListener('click',()=>proxy('career-open-progress'));for(const b of root.querySelectorAll('[data-upgrade]'))b.onclick=()=>{const legacy=document.querySelector(`#career-upgrades [data-upgrade="${CSS.escape(b.dataset.upgrade)}"]`);legacy?.click();setTimeout(queueRefresh,0);};for(const b of root.querySelectorAll('[data-player-id]'))b.onclick=()=>{const legacy=document.querySelector(`#my-team-roster [data-player-id="${CSS.escape(b.dataset.playerId)}"]`);legacy?.click();};}
function refresh(){refreshQueued=false;snapshot=buildSnapshot();const screen=el('career-screen');if(!snapshot){root.hidden=true;screen?.classList.remove('mobile-app-active');return;}screen.classList.add('mobile-app-active');root.hidden=false;renderApp();}
function queueRefresh(){if(refreshQueued)return;refreshQueued=true;queueMicrotask(refresh);}

export function initMobileCareerApp(){
 if(!document.getElementById('mobile-career-app-style')){const style=document.createElement('style');style.id='mobile-career-app-style';style.textContent=STYLE;document.head.appendChild(style);}
 const screen=el('career-screen');if(!screen)return;
 root=document.createElement('section');root.id='mobile-career-app';root.hidden=true;root.setAttribute('aria-label','Career mobile app');screen.appendChild(root);
 new MutationObserver(queueRefresh).observe(screen,{attributes:true,attributeFilter:['class']});
 const hub=el('career-hub');if(hub)new MutationObserver(queueRefresh).observe(hub,{attributes:true,attributeFilter:['hidden']});
 const level=el('career-header-level');if(level)new MutationObserver(queueRefresh).observe(level,{childList:true,characterData:true,subtree:true});
 const roster=el('my-team-roster');if(roster)new MutationObserver(queueRefresh).observe(roster,{childList:true});
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)queueRefresh();});
 queueRefresh();setTimeout(queueRefresh,120);
}
